































100%|████████████████████████████████████████████▉| 3367/3375 [01:04<00:00, 50.55it/s]

100%|█████████████████████████████████████████████| 3375/3375 [01:04<00:00, 52.13it/s]
train accuracy = 0.8163703703703704; train loss = 0.13144394472840537
validation accuracy = 0.8125; validation loss = 0.13376347392688218






































 98%|████████████████████████████████████████████▎| 3319/3375 [01:16<00:00, 69.24it/s]

100%|█████████████████████████████████████████████| 3375/3375 [01:17<00:00, 43.80it/s]
train accuracy = 0.8479444444444444; train loss = 0.11065092463886525
validation accuracy = 0.8435; validation loss = 0.11489621398011504
































 98%|████████████████████████████████████████████▏| 3311/3375 [01:04<00:01, 43.17it/s]

100%|█████████████████████████████████████████████| 3375/3375 [01:06<00:00, 50.84it/s]
train accuracy = 0.8524074074074074; train loss = 0.10672279072717772
validation accuracy = 0.8458333333333333; validation loss = 0.11115220029350498




 15%|██████▊                                       | 496/3375 [00:10<00:58, 49.64it/s][34m[1mwandb[39m[22m: Ctrl + C detected. Stopping sweep.
 15%|███████                                       | 517/3375 [00:11<01:07, 42.11it/s]Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/linecache.py", line 46, in getlines
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/codecs.py", line 319, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "/home/vikram/Desktop/Deep Learning/cs6910_assignment1/mse_vs_ce_loss.py", line 95, in <module>
    for conf in configs:
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/wandb_sweep.py", line 112, in sweep
    sweep_id, warnings = api.upsert_sweep(sweep)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/apis/internal.py", line 102, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2283, in upsert_sweep
    response = self.gql(
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 214, in gql
    ret = self._retry_gql(
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/home/vikram/miniconda3/envs/dlenv/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt